config/routes.rb
Alballery::Application.routes.draw do
  root :to => 'pages#home'
  devise_for :users

  resources :albums
end

app/models/album.rb
class Album < ActiveRecord::Base
  # - Accessible Attributes - #
  attr_accessible :artist, :title, :year, :cover, :cover_cache

  # - Relationships - #
  belongs_to :user

  # - Validations - #
  validates_presence_of :title, :artist, :year, :user_id
  validates_numericality_of :year, :greater_than => 0

  # - CarrierWave - #
  mount_uploader :cover, AlbumCoverUploader

  # - Instance Methods - #
  def owner?(user)
    self.user.eql? user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # - Devise - #
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # - Relationships - #
  has_many :albums

  # - Accessible Attributes - #
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/albums_controller.rb
class AlbumsController < InheritedResources::Base
  before_filter :authenticate_user!, :except => :index
  respond_to :html, :json

  def index
    respond_with(@albums = Album.all)
  end

  protected

    def begin_of_association_chain
      current_user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_messages
    {
      :alert   => 'alert',
      :notice  => 'alert alert-success',
      :error   => 'alert alert-error',
      :success => 'alert alert-success',
      :info    => 'alert alert-info'
    }.map do |key, val|
      content_tag :div, flash[key], :class => val if flash[key]
    end.join.html_safe
  end

  def session_links
    if user_signed_in?
      raw(
        current_user.email +
        ' | ' +
        link_to('Sign out', destroy_user_session_path)
      )
    else
      raw(
        link_to('Sign in', new_user_session_path) +
        ' or ' +
        link_to('Sign up', new_user_registration_path)
      )
    end
  end

  def error_messages_for(object)
    if object.errors.any?
      content_tag :div, :id => 'error_explanation' do
        raw(
          content_tag(:h2, "#{pluralize(object.errors.count, "error")} prohibited this ticket from being saved:") +
          content_tag(:ul) { object.errors.full_messages.map { |m| content_tag(:li, m) }.join.html_safe }
        )
      end
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/albums/_album.html.slim
li.span2
  .thumbnail
    = image_tag album.cover.url(:thumb)
    .caption
      h5 = album.title
      p
        i = album.artist
      p
        b = album.year
      - if user_signed_in? and album.owner?(current_user)
        span = link_to t('.edit', :default => t("helpers.links.edit")), edit_album_path(album), :class => 'btn btn-mini'
        '
        span.pull-right = link_to t('.destroy', :default => t("helpers.links.destroy")), album_path(album), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

app/views/albums/_form.html.slim
= form_for resource, :html => { :class => "form-horizontal" } do |f|
  = error_messages_for resource
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'

  .control-group
    = f.label :year, :class => 'control-label'
    .controls
      = f.text_field :year, :class => 'number_field'

  .control-group
    = f.label :artist, :class => 'control-label'
    .controls
      = f.text_field :artist, :class => 'text_field'

  .control-group
    = f.label :cover, :class => 'control-label'
    .controls= image_tag resource.cover.url(:thumb)

  .control-group
    .controls
      = f.file_field :cover, :class => 'text_field'
      = f.hidden_field :cover_cache

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), albums_path, :class => 'btn'

app/views/albums/edit.html.slim
- model_class = @album.class
h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/albums/index.html.slim
.well
  h1 Albums

= link_to t('.new', :default => t("helpers.links.new")), new_album_path, :class => 'btn btn-primary'

.clearfix

br/

ul.thumbnails.albums
  = render @albums

app/views/albums/new.html.slim
- model_class = @album.class
h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/albums/show.html.slim
- model_class = @album.class
h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:title) + ':'
  br
  = @album.title
p
  strong= model_class.human_attribute_name(:year) + ':'
  br
  = @album.year
p
  strong= model_class.human_attribute_name(:artist) + ':'
  br
  = @album.artist

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), albums_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_album_path(@album), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), album_path(@album), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Alballery"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico'

  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="#"Alballery
          .container.nav-collapse
            ul.nav
              li= link_to 'Home', root_path
              li= link_to 'Albums', albums_path
            p.navbar-text.pull-right = session_links

    .container
      .content
        .row = flash_messages
        .row
          .span12 = yield

      footer
        p &copy; Company 2012

    = javascript_include_tag "application"

app/views/layouts/devise.html.slim
doctype 5
html
  head
    title Alballery
    = csrf_meta_tags
    / Le styles
    = stylesheet_link_tag 'application'

    / Le javascripts
    = javascript_include_tag 'application'

  body.devise
    / Top Navigation bar
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          div= link_to 'Alballery', root_path, :class => 'brand'
          .nav-collapse
            ul.nav
              li= link_to 'Home', root_path

    / Body content
    - flash.keys.each do |k|
      .container.alert = flash[k]
    .well.span5.center = yield

app/views/pages/home.html.slim
.hero-unit
  h1 Create and manage your music albums.
  p
    ' Start by
    ' signing up or signing in.